MVCProJect/Controllers/ApiConroller/CustomerController.cs
using AutoMapper;
using MVCProJect.Dtos;
using MVCProJect.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Data.Entity;

namespace MVCProJect.Controllers.ApiConroller
{
	public class CustomerController : ApiController
	{
		private ApplicationDbContext _ctx;
		public CustomerController()
		{
			_ctx = new ApplicationDbContext();
		}

		//GET Api/Customers
		[HttpGet]
		public IEnumerable<CustomerDto> GetAll(string query =null)
		{
			var CustomersQuery = _ctx.Customers
				.Include(c => c.Membership);
			if (!string.IsNullOrWhiteSpace(query))
				CustomersQuery = CustomersQuery.Where(c => c.Name.Contains(query));
			var CustomerDto = CustomersQuery
				.ToList()
				.Select(Mapper.Map<Customer,CustomerDto>);
			return CustomerDto;
		}
		[HttpGet]
		public IHttpActionResult GetCustomer(int Id)
		{
			var customer = _ctx.Customers.SingleOrDefault(c => c.Id == Id);
			if (customer == null)
			{
				return NotFound();
			}

			return Ok(Mapper.Map<Customer,CustomerDto> (customer));
		}

		[HttpPost]

		public IHttpActionResult PostCustomer(CustomerDto customerdto)
		{
			if (!ModelState.IsValid)

				return BadRequest();
			var customer = Mapper.Map<CustomerDto, Customer>(customerdto);
			_ctx.Customers.Add(customer);
			_ctx.SaveChanges();

			return Created(new Uri (Request.RequestUri+"/"+customer.Id),customerdto);

		}
		[HttpPut]
		public void UpdateCustomer(int Id, CustomerDto customerdto)

		{
			var customerInDB = _ctx.Customers.SingleOrDefault(c => c.Id == Id);

			if (customerInDB == null)
				throw new HttpResponseException(HttpStatusCode.NotFound);

			if (!ModelState.IsValid)

				throw new HttpResponseException(HttpStatusCode.BadRequest);

			Mapper.Map(customerdto , customerInDB);

			//customerInDB.Name = customer.Name;
			//customerInDB.MembershipId = customer.MembershipId;
			//customerInDB.BirthDate = customer.BirthDate;
			//customerInDB.IsSubscribedToNewsLetters = customer.IsSubscribedToNewsLetters;
			_ctx.SaveChanges();
		}

			public void DeleteCustomer(int Id)

		{
			var customer = _ctx.Customers.SingleOrDefault(c => c.Id == Id);
			if (customer == null)
			{
				throw new HttpResponseException(HttpStatusCode.NotFound);
			}

			_ctx.Customers.Remove(customer);
			_ctx.SaveChanges();
		}

    }
}

MVCProJect/Controllers/ApiConroller/MusicInstrumentsController.cs
using AutoMapper;
using MVCProJect.Dtos;
using MVCProJect.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Data.Entity;
using System.Web.Http;

namespace MVCProJect.Controllers.ApiConroller
{
	public class MusicInstrumentsController : ApiController
	{
		private ApplicationDbContext _ctx;
		public MusicInstrumentsController()
		{
			_ctx = new ApplicationDbContext();
		}
		[HttpGet]
		public IEnumerable<MusicInstrumentDto> MusicInstruments(string query=null)
		{
			var musicQuery = _ctx.MusicInstruments.
				Include(c => c.Genre);
			if (!string.IsNullOrWhiteSpace(query))
				musicQuery = musicQuery.Where(m=>m.Name.Contains(query));
			var musicDto = musicQuery
				.ToList()
				.Select(Mapper.Map<MusicInstruments,MusicInstrumentDto>);
			return musicDto;
		}
		[HttpGet]

		public IHttpActionResult MusicInstrument(int Id)
		{
			var music = _ctx.MusicInstruments.SingleOrDefault(c => c.Id == Id);
			if (music == null)
				return NotFound();

			return Ok(Mapper.Map<MusicInstruments,MusicInstrumentDto>(music));
		}

		[HttpPost]
		public IHttpActionResult MusicInstrument(MusicInstrumentDto MusicInstrumentdto)
		{
			if (!ModelState.IsValid)
				return BadRequest();
			var MusicInstrument = Mapper.Map<MusicInstrumentDto, MusicInstruments>(MusicInstrumentdto);
			_ctx.MusicInstruments.Add(MusicInstrument);
			_ctx.SaveChanges();
			return Created(new Uri (Request.RequestUri+"/"+ MusicInstrument.Id),MusicInstrument);
		}

		[HttpPut]
		public void UpdateMusicInstrument(int Id, MusicInstrumentDto MusicInstrumentdto)
		{
			var music = _ctx.MusicInstruments.SingleOrDefault(c => c.Id == Id);

			if (music == null)
				throw new HttpResponseException(HttpStatusCode.NotFound);

			if (!ModelState.IsValid)
				throw new HttpResponseException(HttpStatusCode.BadRequest);
			//using Auto mapper
			Mapper.Map(MusicInstrumentdto , music);

			//music.Name = MusicInstrument.Name;
			//music.InstructorName = MusicInstrument.InstructorName;
			//music.GenreId = MusicInstrument.GenreId;
			//music.CourseDuration = MusicInstrument.CourseDuration;
			_ctx.SaveChanges();
		}
		[HttpDelete]
		public void DeleteInstrument(int Id)
		{
			var music = _ctx.MusicInstruments.SingleOrDefault(c => c.Id == Id);

			if (music == null)
				throw new HttpResponseException(HttpStatusCode.NotFound);
			_ctx.MusicInstruments.Remove(music);
			_ctx.SaveChanges();
		}



	}
}

MVCProJect/Controllers/UMLController.cs
using MVCProJect.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCProJect.Controllers
{
	[Authorize(Roles = RoleName.CanManageRoles)]
	public class UMLController : Controller
    {
        // GET: UML
        public ActionResult Index()
        {
            return View();
        }
    }
}

MVCProJect/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title - Tera Music</title>
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")

</head>
<body>
	<div id="navbar" class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				@Html.ActionLink("Tera Music", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li>@Html.ActionLink(" Home", "Index", "Home", null, new { @class = "glyphicon glyphicon-home" })</li>
					<li>@Html.ActionLink(" Customer", "Index", "Customer" , null, new { @class= "glyphicon glyphicon-th-list" })</li>
					<li>@Html.ActionLink(" Rental", "Index", "UML", null, new { @class = "glyphicon glyphicon-headphones" })</li>
					<li>@Html.ActionLink(" Insruments", "Index", "MusicInstruments", null, new { @class = "glyphicon glyphicon-music" })</li>
					<li>@Html.ActionLink(" About", "About", "Home", null, new { @class = "glyphicon glyphicon-info-sign" })</li>
					<li>@Html.ActionLink(" Contact", "Contact", "Home", null, new { @class = "glyphicon glyphicon-envelope" })</li>
				</ul>
				@Html.Partial("_LoginPartial")
			</div>
		</div>
	</div>

	<div class="container body-content">
		@RenderBody()
	</div>
	<br />


	<!-- Footer -->
	<hr />
	<nav class=" navbar-wrapper navbar-fixed-bottom">
		<div class="container-fluid">
			<p class="navbar-text">&copy; @DateTime.Now.Year - Tera Music. All rights reserved</p>
			<a href="/Account/Register" class="btn navbar-btn button ">Subscribe</a>
		</div>
	</nav>
	<!-- Footer -->


	@Scripts.Render("~/bundles/lib")
	@RenderSection("scripts", required: false)
	<script>
		$(document).ready(function () {
			$(window).scroll(function () {
				'use strict';
				if ($(window).scrollTop() >= $('#navbar').height()) {
					$('#navbar').addClass("scrolled");
				}
				else {
					$('#navbar').removeClass("scrolled");
				}
			});
			$('.navbar-nav ').on("click", "li", function () {
				$(this).addClass('active');
			});
		});
	</script>

</body>
</html>